### ISSUE TITLE
Incompatibility with rack-test and Haml > 5.0 (options method)

### ISSUE THREAD

**Issue by DangerDawson** [judofyr/temple#120] opened 2018-08-28 07:08 UTC
When running specs the HTTP options method:

https://github.com/rack-test/rack-test/blob/master/lib/rack/test.rb#L97

```
def options(uri, params = {}, env = {}, &block)
  custom_request('OPTIONS', uri, params, env, &block)
end

```
Is being called below by f

https://github.com/judofyr/temple/blob/378c47ffebed2915635cd6c759ce0834e3d4a2d6/lib/temple/mixins/engine_dsl.rb#L101

Which is not the expected behaviour, and is preventing rack-test being run.

I have temporarily fixed this by removing the options method from rack-test, although this is not the correct solution.

Any thoughts on this?

I have raised a ticket regarding this with rack-test as well

https://github.com/rack-test/rack-test/issues/236#issuecomment-415842597

**Comment by judofyr** [comment] 2018-09-01 16:17
Exactly what command/code is it that is failing?

**Comment by DangerDawson** [comment] 2018-09-02 09:11
The error manifests it's self when rendering a view whilst running the tests with rack-test e.g.

```ruby
get '/users/new'
``` 

Will cause the following error:

```
     ArgumentError:
       wrong number of arguments (given 0, expected 1..3)
```

Which is happening due to

```ruby
def options(uri, params = {}, env = {}, &block)
  custom_request('OPTIONS', uri, params, env, &block)
end
```

Overriding the options method defined on f below:

```ruby
 f.new(f.respond_to?(:options) ? engine.options.to_hash.select {|k,v| f.options.valid_key?(k) } : engine.options)
```

**Comment by JoeHampton** [comment] 2018-09-19 20:28
I've been having the exact same issue in one of my applications, pointing to the same line you found. I also have another application with the same versions of haml, temple, and rack-test, and this issue is not happening with it. The difference is that the working application doesn't ever have f.respond_to?(:options) return true.

That may just be a coincidence though. I haven't poked around too long to understand the differences in the temple filters that are being used by the working and non-working applications.

**Comment by judofyr** [comment] 2018-09-20 18:06
It's been a while since I've looked at these methods so I'm a bit confused to what is happening. Does any of you have a reproducible example you can share? That is, all files (including `Gemfile` and `Gemfile.lock`)?

**Comment by DannySantos** [comment] 2018-10-11 11:01
I've recreated the issue in a barebones Roda app:

https://github.com/DannySantos/roda_spec_bug

Details in the readme.

**Comment by judofyr** [comment] 2018-10-11 11:02
Very much appreciated! I'll look at it later and try to figure it out, although to be honest it's been a while since I've been looking at Temple/Slim.

**Comment by h0jeZvgoxFepBQ2C** [comment] 2021-10-19 12:09
The strange thing is that this happens also with a normal string? lol

```ruby
[5] pry(Haml::TempleEngine)> "asdasdas".options
ArgumentError: wrong number of arguments (given 0, expected 1..3)
from /Users/user/.rvm/gems/ruby-2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:97:in `options'
```

**Comment by k0kubun** [comment] 2022-10-25 08:05
Looks like people have figured it out, so closing this. Thank you.

**Closed by k0kubun** 2022-10-25 08:05 UTC
